/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Public_pagesRouteImport } from './routes/_public_pages'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as Public_pagesIndexRouteImport } from './routes/_public_pages/index'
import { Route as Public_pagesAboutRouteImport } from './routes/_public_pages/about'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicSigninRouteImport } from './routes/_public/signin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExpensesExpenseIdRouteImport } from './routes/_authenticated/expenses/$expenseId'

const Public_pagesRoute = Public_pagesRouteImport.update({
  id: '/_public_pages',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const Public_pagesIndexRoute = Public_pagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Public_pagesRoute,
} as any)
const Public_pagesAboutRoute = Public_pagesAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => Public_pagesRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSigninRoute = PublicSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesExpenseIdRoute =
  AuthenticatedExpensesExpenseIdRouteImport.update({
    id: '/expenses/$expenseId',
    path: '/expenses/$expenseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof Public_pagesIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/signin': typeof PublicSigninRoute
  '/signup': typeof PublicSignupRoute
  '/about': typeof Public_pagesAboutRoute
  '/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof Public_pagesIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/signin': typeof PublicSigninRoute
  '/signup': typeof PublicSignupRoute
  '/about': typeof Public_pagesAboutRoute
  '/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public_pages': typeof Public_pagesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_public/signin': typeof PublicSigninRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public_pages/about': typeof Public_pagesAboutRoute
  '/_public_pages/': typeof Public_pagesIndexRoute
  '/_authenticated/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/about'
    | '/expenses/$expenseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/about'
    | '/expenses/$expenseId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_public_pages'
    | '/_authenticated/dashboard'
    | '/_public/signin'
    | '/_public/signup'
    | '/_public_pages/about'
    | '/_public_pages/'
    | '/_authenticated/expenses/$expenseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  Public_pagesRoute: typeof Public_pagesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public_pages': {
      id: '/_public_pages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Public_pagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public_pages/': {
      id: '/_public_pages/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Public_pagesIndexRouteImport
      parentRoute: typeof Public_pagesRoute
    }
    '/_public_pages/about': {
      id: '/_public_pages/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof Public_pagesAboutRouteImport
      parentRoute: typeof Public_pagesRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signin': {
      id: '/_public/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PublicSigninRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/$expenseId': {
      id: '/_authenticated/expenses/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof AuthenticatedExpensesExpenseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesExpenseIdRoute: typeof AuthenticatedExpensesExpenseIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesExpenseIdRoute: AuthenticatedExpensesExpenseIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicSigninRoute: typeof PublicSigninRoute
  PublicSignupRoute: typeof PublicSignupRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSigninRoute: PublicSigninRoute,
  PublicSignupRoute: PublicSignupRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface Public_pagesRouteChildren {
  Public_pagesAboutRoute: typeof Public_pagesAboutRoute
  Public_pagesIndexRoute: typeof Public_pagesIndexRoute
}

const Public_pagesRouteChildren: Public_pagesRouteChildren = {
  Public_pagesAboutRoute: Public_pagesAboutRoute,
  Public_pagesIndexRoute: Public_pagesIndexRoute,
}

const Public_pagesRouteWithChildren = Public_pagesRoute._addFileChildren(
  Public_pagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  Public_pagesRoute: Public_pagesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
